on:
  push:
    branches:
    - main

name: Tests

jobs:
  testing:
    name: Testing the app
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      
      - name: testing
        run: python3 tests.py
